name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove possible .npmrc
        run: rm -f $HOME/.npmrc .npmrc
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Use public npm registry
        run: npm config set registry https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Run backend tests
        run: npm run test

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove possible .npmrc
        run: rm -f $HOME/.npmrc .npmrc
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Use public npm registry
        run: npm config set registry https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Run frontend tests
        run: npm run test:frontend
      - name: Build frontend
        run: npm run build 
