name: Deploy to Render and Vercel

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '**/README.md'

jobs:
  deploy-render:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  deploy-vercel:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Deploy to Vercel
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
